Repository iris-hep/iris-hep.github.io, pull requests merged in 2022-08, with the labels that each got.

#1550 talk: Add Feickert SciPy 2022 lightning talk
  _data/people/matthewfeickert.yml
Labels: Analysis Systems

#1557 talk: Add June 2022 DOEPy talk
  _data/people/matthewfeickert.yml
Labels: Analysis Systems, DOMA

#1558 talk: Add Feickert ICHEP 2022 pyhf talk
  _data/people/matthewfeickert.yml
Labels: Analysis Systems

#1559 pyhf: Add July 2022 use citations
  pages/projects/pyhf.md
Labels: Analysis Systems

#1540 feat: Add Matthew as Analysis Systems Area Lead
  _data/orgs/exec-board.yml
  _data/people/matthewfeickert.yml
Labels: Analysis Systems

#1560 July, August 2022 presentations from Jim
  _data/people/jpivarski.yml
Labels: Analysis Systems

#1571 fix: Correct Ridolfi Fellow end date
  pages/fellows/peterridolfi.md
Labels: fix

#1578 chore: Make pyhf to Combine converter Fellow project as completed
  _data/fellow_projects/a_pyhf_converter_for_binned_likelihood_models_in_cms_combine.yml
Labels: Analysis Systems, fellowship-project
