Repository iris-hep/iris-hep.github.io, pull requests merged in 2022-10, with the labels that each got.

#1617 talk: Add Peter Ridolfi's Fellow project summary presentation
  pages/fellows/peterridolfi.md
Labels: Analysis Systems, fellowship-project

#1615 added information about fellowship presentation
  pages/fellows/maxymnaumchyk.md
Labels: fellowship-project

#1619 talk: Add Philip Templeman Fellow intro talk
  pages/fellows/ptemplem.md
Labels: Analysis Systems, fellowship-project

#1642 Update hswhhe.md with final talk info
  pages/fellows/hswhhe.md
Labels: Analysis Systems
